pages:
  image: haskell:8.6.5
  stage: deploy
  script:
  - cabal update
  - cabal build
  - cabal run blog -- clean
  - cabal run blog -- build
  - cp -r _site public
  artifacts:
    paths:
    - public
