cache:
  paths:
  - .cabal

pages:
  image: haskell:8.6.5
  stage: deploy
  script:
  - cabal new-update
  - cabal new-build
  - cabal new-run blog -- clean
  - cabal new-run blog -- build
  - cp -r _site public
  artifacts:
    paths:
    - public
