cache:
  paths:
  - .cabal/packages
  - .cabal/store
  - dist
  - dist-newstyle

pages:
  image: haskell:8.6.5
  stage: deploy
  script:
  - cabal --store-dir .cabal new-update
  - cabal --store-dir .cabal new-build
  - cabal --store-dir .cabal new-run blog -- clean
  - cabal --store-dir .cabal new-run blog -- build
  - cp -r _site public
  artifacts:
    paths:
    - public
