name: "Hakyll"

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-20.03

    # Build the site using Nix.
    - name: Build site
      run: |
        nix run -c site build

    # Deploy the site to GitHub pages.
    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        publish_branch: master
